---
title: "Median gross earnings, ASHE data"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
```

```{r prep_data}
source("R/earnings_charts.R")
```


Weekly
================

Column
-------------------------------------

### All employees

```{r}

charts_earnings$weekly_all

```

Column {.tabset}
-----------------------------------

### Full-time employees

```{r}

charts_earnings$weekly_FT

```

### Part-time employees

```{r}

charts_earnings$weekly_PT

```


Annual
================

Column
-------------------------------------

### All employees

```{r}

charts_earnings$annual_all

```

Column {.tabset}
-------------------------------------

### Full-time employees

```{r}

charts_earnings$annual_FT

```

### Part-time employees

```{r}

charts_earnings$annual_PT

```

Hourly
================

Column
-------------------------------------

### All employees

```{r}

charts_earnings$hourly_all

```

Column {.tabset}
-------------------------------------

### Full-time employees

```{r}

charts_earnings$hourly_FT

```

### Part-time employees

```{r}

charts_earnings$hourly_PT

```

