---
title: "Median gross earnings in real terms, ASHE data"
output: 
  flexdashboard::flex_dashboard:
    navbar: 
      - { title: "NOMINAL PAY", href: "index.html", align: right }
    vertical_layout: fill

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(highcharter)
```

```{r prep_data}

charts_earnings <- readRDS("data/charts_earnings.rds")

```

# Weekly

## Column

### All employees

```{r}

charts_earnings$weekly_all_real

```

## Column {.tabset}

### Full-time employees

```{r}

charts_earnings$weekly_FT_real

```

### Part-time employees

```{r}

charts_earnings$weekly_PT_real

```

# Annual

## Column

### All employees

```{r}

charts_earnings$annual_all_real

```

## Column {.tabset}

### Full-time employees

```{r}

charts_earnings$annual_FT_real

```

### Part-time employees

```{r}

charts_earnings$annual_PT_real

```

# Hourly

## Column

### All employees

```{r}

charts_earnings$hourly_all_real

```

## Column {.tabset}

### Full-time employees

```{r}

charts_earnings$hourly_FT_real

```

### Part-time employees

```{r}

charts_earnings$hourly_PT_real

```
