---
title: "Central Scotland"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
---
  
```{r setup, include = FALSE}

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

```{r prep_data}

library(highcharter)

x <- "Central Scotland"

```

```{r housing}

# Housing

charts_housing <- readRDS("data/charts_housing.rds")

# add layout and charts by looping through regions
title1 <- "# Housing"
sidebar1 <- paste0("## Sidebar {.sidebar}\n",
                  knitr::knit_expand("dashboard/_sidebar_text/housing_text.Rmd"))
layout1 <- knitr::knit_expand('dashboard/_layouts/housing_layout.Rmd')

title1 = knitr::knit_child(text = unlist(title1), quiet = TRUE)
sidebar1 <- knitr::knit_child(text = unlist(sidebar1), quiet = TRUE)
layout1 = knitr::knit_child(text = unlist(layout1), quiet = TRUE)

```

```{r pay}

# Pay

charts_n <- readRDS("data/charts_earnings.rds")[["regions"]][["nominal"]]
charts_r <- readRDS("data/charts_earnings.rds")[["regions"]][["real"]]
charts_l <- readRDS("data/charts_earnings.rds")[["regions"]][["latest"]]

# add layout and charts by looping through regions
title2 <- "# Pay"
sidebar2 <- paste0("## Sidebar {.sidebar}\n",
                  knitr::knit_expand("dashboard/_sidebar_text/earnings_text.Rmd"))
layout2 <- knitr::knit_expand('dashboard/_layouts/earnings_layout.Rmd')

title2 = knitr::knit_child(text = unlist(title2), quiet = TRUE)
sidebar2 <- knitr::knit_child(text = unlist(sidebar2), quiet = TRUE)
layout2 = knitr::knit_child(text = unlist(layout2), quiet = TRUE)

```

```{r output, results='asis'}
cat(title1, sidebar1, layout1,
    title2, sidebar2, layout2, sep = '\n')

```


