## SIMD  {data-height=350}

### {{x}} SIMD overview {.first-box}
```{r}
charts_deprivation$barchart$SIMD[["{{x}}"]]
```

### {{x}} SIMD map {.first-box}
```{r}
charts_deprivation$region_maps$SIMD[["{{x}}"]]
```

## Row {data-height=300}

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[1]]
```

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[2]]
```

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[3]]
```

## Row {data-height=300}

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[4]]
```

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[5]]
```

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[6]]
```

## Row {data-height=300}

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[7]]
```

### Constituency {.no-title}
```{r}
charts_deprivation$const_maps$SIMD[["{{x}}"]][[8]]
```

### Constituency {.no-title}
```{r}
try(charts_deprivation$const_maps$SIMD[["{{x}}"]][[9]], silent = TRUE)
```

```{r}
# Some regions have 10 constituencies and need another row for charts 
is10 <- length(charts_deprivation$const_maps$SIMD[["{{x}}"]]) == 10
```

```{r eval=is10, results = 'asis'}

out <- list(knitr::knit_expand(text = "## Row 5 {data-height=300} \n"),
            knitr::knit_expand(text = "### Constituency {data-width=1 .no-title} \n"),
            knitr::knit_expand(text = "`r charts_deprivation$const_maps$SIMD[['{{x}}']][[10]]` \n"),
            knitr::knit_expand(text = "### Empty box {data-width=2 .no-title .empty-box}"))

res = knitr::knit_child(text = unlist(out), quiet = TRUE)
cat(res, sep = '\n')

```

