## Row 1 {data-height=350}

### Unemployment (claimant count) {.first-box}

```{r}
charts_unemp[["{{x}}"]]
```

### Employment {.first-box}

```{r}
charts_emp[["{{x}}"]]
```

### Inactivity {.first-box}

```{r}
charts_inact[["{{x}}"]]
```

## Row 2 {data-height=300}

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[1]]
```

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[2]]
```

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[3]]
```

## Row 3 {data-height=300}

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[4]]
```

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[5]]
```

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[6]]
```

## Row 4 {data-height=300}

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[7]]
```

### Constituency {.no-title}

```{r}
charts_c[["{{x}}"]][[8]]
```

### Constituency {.no-title}

```{r}
try(charts_c[["{{x}}"]][[9]], silent = TRUE)
```

```{r}
# Some regions have 10 constituencies and need another row for charts 
is10 <- length(charts_c[["{{x}}"]]) == 10
```

```{r eval=is10, results = 'asis'}

out <- list(knitr::knit_expand(text = "## Row 5 {data-height=300} \n"),
            knitr::knit_expand(text = "### Constituency {data-width=1 .no-title} \n"),
            knitr::knit_expand(text = "`r charts_c[['{{x}}']][[10]]` \n"),
            knitr::knit_expand(text = "### Empty box {data-width=2 .no-title .empty-box}"))

res = knitr::knit_child(text = unlist(out), quiet = TRUE)
cat(res, sep = '\n')

```
